---
elasticsearch_state: present
elasticsearch_install_method: s3
elasticsearch_install_path: /opt
elasticsearch_version: 1.4.2
elasticsearch_remove_old: true
elasticsearch_s3_bucket:
elasticsearch_s3_base:
elasticsearch_user: elasticsearch
elasticsearch_path_logs: /var/log/elasticsearch
elasticsearch_path_conf: /etc/elasticsearch/conf
elasticsearch_path_work:
elasticsearch_path_plugins:
elasticsearch_path_data:
elasticsearch_java_home:
elasticsearch_autostart: true
elasticsearch_supervisor_state: started
elasticsearch_remove_old: true

### Non Defaulted but available
#elasticsearch_plugins:
#elasticsearch_max_open_files:
#elasticsearch_max_locked_memory:
#elasticsearch_heap_size:
#elasticsearch_heap_newsize:
#elasticsearch_direct_size:
#elasticsearch_java_opts:
#elasticsearch_cluster_name
#elasticsearch_cluster_routing_allocation_awareness_attributes
#elasticsearch_node_name
#elasticsearch_node_master
#elasticsearch_node_data
#elasticsearch_node_max_local_storage_nodes
#elasticsearch_node_extras
#elasticsearch_index_number_of_shards
#elasticsearch_index_number_of_replicas
#elasticsearch_path_conf
#elasticsearch_path_data
#elasticsearch_path_work
#elasticsearch_path_logs
#elasticsearch_path_plugins
#elasticsearch_plugin_mandatory
#elasticsearch_bootstrap_mlockall
#elasticsearch_network_bind_host
#elasticsearch_network_publish_host
#elasticsearch_network_host
#elasticsearch_transport_tcp_port
#elasticsearch_tcp_compress
#elasticsearch_http_port
#elasticsearch_http_max_content_length
#elasticsearch_http_enabled
#elasticsearch_gateway_type
#elasticsearch_gateway_recover_after_nodes
#elasticsearch_gateway_recover_after_data_nodes
#elasticsearch_gateway_recover_after_master_nodes
#elasticsearch_gateway_recover_after_time
#elasticsearch_gateway_expected_nodes
#elasticsearch_cluster_routing_allocation_node_initial_primaries_recoveries
#elasticsearch_cluster_routing_allocation_node_concurrent_recoveries
#elasticsearch_indices_recovery_max_bytes_per_sec
#elasticsearch_indices_recovery_concurrent_stream
#elasticsearch_discovery_zen_minimum_master_nodes
#elasticsearch_discovery_zen_ping_timeout
#elasticsearch_discovery_zen_ping_multicast_enabled
#elasticsearch_discovery_zen_ping_unicast_hosts
#elasticsearch_index_search_slowlog_threshold_query_warn
#elasticsearch_index_search_slowlog_threshold_query_info
#elasticsearch_index_search_slowlog_threshold_query_debug
#elasticsearch_index_search_slowlog_threshold_query_trace
#elasticsearch_index_search_slowlog_threshold_fetch_warn
#elasticsearch_index_search_slowlog_threshold_fetch_info
#elasticsearch_index_search_slowlog_threshold_fetch_debug
#elasticsearch_index_search_slowlog_threshold_fetch_trace
#elasticsearch_index_search_slowlog_threshold_index_warn
#elasticsearch_index_search_slowlog_threshold_index_info
#elasticsearch_index_search_slowlog_threshold_index_debug
#elasticsearch_index_search_slowlog_threshold_index_trace
#elasticsearch_monitor_jvm_gc_young_warn
#elasticsearch_monitor_jvm_gc_young_info
#elasticsearch_monitor_jvm_gc_young_debug
#elasticsearch_monitor_jvm_gc_old_warn
#elasticsearch_monitor_jvm_gc_old_info
#elasticsearch_monitor_jvm_gc_old_debug
#elasticsearch_script_disable_dynamic
#elasticsearch_http_cors_enabled
#elasticsearch_plugin_aws
#elasticsearch_plugin_aws_ec2_groups
#elasticsearch_plugin_aws_ec2_ping_timeout
#elasticsearch_plugin_aws_access_key
#elasticsearch_plugin_aws_secret_key
#elasticsearch_plugin_aws_region
#elasticsearch_action_auto_create_index
#elasticsearch_action_disable_delete_all_indices
#elasticsearch_conf_additional
