---
- name: get list of installed plugins
  shell: "{{ elasticsearch_path_bin }}/plugin --list"
  register: elasticsearch_installed_plugins

- name: install elasticsearch plugins
  shell: "sudo -E -u {{ elasticsearch_user }} {{ elasticsearch_path_bin }}/plugin --install {{ item.package }} {{ item.options|default('') }}"
  when: item.name is defined and item.name not in elasticsearch_installed_plugins.stdout
  environment:
    JAVA_HOME: "{{ elasticsearch_java_home }}"
  with_items: elasticsearch_plugins
  ignore_errors: yes
