---
- name: Setup Supervisor conf file for Elasticsearch
  template:
    src: elasticsearch.conf.j2
    dest: /etc/supervisor/conf.d/elasticsearch.conf

- name: Register Elasticsearch with supervisorctl
  supervisorctl:
    name: elasticsearch
    state: present
